# Imports

In [1]:
import numpy as np
import math

# Inputs

In [41]:
inputed_elements = input('please enter your elements:')
inputed_elements_array = inputed_elements.split(" ")
Matrix_column_size = len(inputed_elements_array)
chemical_equation = input('please enter your chemical equation:')

please enter your elements:C H O
please enter your chemical equation:C2 H6 + O2 -> C O2 + H2 O


In [68]:
variable_counts = 0
left_chemical_equation = ""
right_chemical_equation = ""
for character_index in range(0,len(chemical_equation)) :
    if(chemical_equation[character_index] == "-"):
         left_chemical_equation=chemical_equation[0:character_index] 
         right_chemical_equation = chemical_equation[character_index+3:len(chemical_equation)]

splitted_left_chemical_equation = left_chemical_equation.split("+")
splitted_right_chemical_equation = right_chemical_equation.split("+")
splitted_right_chemical_equation[len(splitted_right_chemical_equation)-1] = splitted_right_chemical_equation[len(splitted_right_chemical_equation)-1] + " "
variable_counts = len(splitted_left_chemical_equation) + len(splitted_right_chemical_equation)
print(splitted_left_chemical_equation)
print(splitted_right_chemical_equation )

['C2 H6 ', ' O2 ']
['C O2 ', ' H2 O ']


# Agmented Matrix(n,m)

n = Matrix_column_size</br>
m = variable_counts

In [282]:
agmented_matrix = np.arange(0,(variable_counts+1)*Matrix_column_size,dtype='float').reshape(Matrix_column_size,variable_counts+1)*0

for row_index in range(0,Matrix_column_size):
    cul_index = -1
    for left_string in splitted_left_chemical_equation :
        cul_index -=-1
        if inputed_elements_array[row_index] in left_string:
               for index_elements in range(0,len(left_string)):
                    if(left_string[index_elements] == inputed_elements_array[row_index]):
                        if(left_string[index_elements+1] == " ") : agmented_matrix[row_index,cul_index] = 1
                        else :    
                            agmented_matrix[row_index,cul_index] = int(left_string[index_elements+1])
        else : agmented_matrix[row_index,cul_index] = 0
    
    for right_string in splitted_right_chemical_equation :
        cul_index -=-1
        if inputed_elements_array[row_index] in right_string:
               for index_elements in range(0,len(right_string)):
                    if(right_string[index_elements] == inputed_elements_array[row_index]):
                        if(right_string[index_elements+1] == " ") : agmented_matrix[row_index,cul_index] = -1
                        else :
                            agmented_matrix[row_index,cul_index] = int(right_string[index_elements+1])
                            agmented_matrix[row_index,cul_index] *=-1
        else : agmented_matrix[row_index,cul_index] = 0
        
print(f"Agmented Matrix :\n{agmented_matrix}" ) 

Agmented Matrix :
[[ 2.  0. -1.  0.  0.]
 [ 6.  0.  0. -2.  0.]
 [ 0.  2. -2. -1.  0.]]


# sorte Agmented Matrix by pivot position

Here I check where exactly in each row the piviot line is located to arrange the lines by using one of the principles of the applied linear algebra lesson with the line reduction operation so that the axial lines and rows are in better order. Have for Ashlon forms

In [283]:
sorted_agmented_matrix = np.arange(0,(variable_counts+1)*Matrix_column_size,dtype='float').reshape(Matrix_column_size,variable_counts+1)*0
piviot_array = np.arange(0,2*Matrix_column_size).reshape(Matrix_column_size,2)*0

compaired_row = 0
for row in agmented_matrix:
    compair_culomn_index = -1
    for cul_index in range(0,variable_counts):
      compair_culomn_index -=-1
      if row[cul_index] != 0:
         if cul_index+1 in piviot_array[:, -1] :
            pass
         else:
            piviot_array[compaired_row,0] = compaired_row
            piviot_array[compaired_row,1] = cul_index+1
            break
    compaired_row-=-1  

piviot_array = piviot_array[piviot_array[:,-1].argsort()]
print(piviot_array)
row_index = 0
for row in piviot_array :
    row_number = row[0]
    sorted_agmented_matrix[row_index] = agmented_matrix[row_number]
    row_index-=-1

sorted_agmented_matrix

[[0 1]
 [2 2]
 [1 4]]


array([[ 2.,  0., -1.,  0.,  0.],
       [ 0.,  2., -2., -1.,  0.],
       [ 6.,  0.,  0., -2.,  0.]])

Convert piviot positions to one

In [284]:
row_index = 0
for row in sorted_agmented_matrix :
    for cul_index in range(0,variable_counts):
      if row[cul_index] != 0 :
        sorted_agmented_matrix[row_index] /= row[cul_index]
        break
    row_index-=-1
agmented_matrix = sorted_agmented_matrix

In [285]:
print(sorted_agmented_matrix)

[[ 1.          0.         -0.5         0.          0.        ]
 [ 0.          1.         -1.         -0.5         0.        ]
 [ 1.          0.          0.         -0.33333333  0.        ]]


# Formation Of Ashlon Matrix

Here I form the Ashlon matrix form, to obtain which we must convert all non-zero data to zero in the corresponding columns of the row rows with row operations and move from row to bottom in the rows.

In [286]:
Column_index = -1
for row_index in range(0,Matrix_column_size):
    Column_index -=-1
    for second_row_index in range(row_index+1,Matrix_column_size):
        if Column_index == variable_counts+1 or row_index == Matrix_column_size :
            break
        if agmented_matrix[second_row_index,Column_index] != 0 and agmented_matrix[row_index,Column_index] == 1:
            agmented_matrix[second_row_index] -= agmented_matrix[row_index]*agmented_matrix[second_row_index,Column_index]
agmented_matrix

array([[ 1.        ,  0.        , -0.5       ,  0.        ,  0.        ],
       [ 0.        ,  1.        , -1.        , -0.5       ,  0.        ],
       [ 0.        ,  0.        ,  0.5       , -0.33333333,  0.        ]])

Convert piviot positions to one

In [287]:
row_index = 0
for row in agmented_matrix :
    for cul_index in range(0,variable_counts):
      if row[cul_index] != 0 :
        agmented_matrix[row_index] /= row[cul_index]
        break
    row_index-=-1
agmented_matrix

array([[ 1.        ,  0.        , -0.5       ,  0.        ,  0.        ],
       [ 0.        ,  1.        , -1.        , -0.5       ,  0.        ],
       [ 0.        ,  0.        ,  1.        , -0.66666667,  0.        ]])

# Converting the Ashlon form to the reduced Ashlon form

Here I change the form of the Ashlon matrix to a reduced Ashlon, which this time, unlike the previous series, I have to go through the rows from the bottom up, and if I hit the column corresponding to the axis in the higher rows, which was not zero, add the rows Zero it.

In [288]:
row_index = Matrix_column_size -1
Column_index = variable_counts -2
while row_index > -1:
    print(Column_index)
    second_row_index = row_index - 1
    while second_row_index > -1:
        if agmented_matrix[second_row_index,Column_index] != 0 and agmented_matrix[row_index,Column_index] == 1:
            agmented_matrix[second_row_index] -= agmented_matrix[row_index]*agmented_matrix[second_row_index,Column_index]
        second_row_index -=1 
    Column_index-=1
    row_index -=1
print(agmented_matrix)

2
1
0
[[ 1.          0.          0.         -0.33333333  0.        ]
 [ 0.          1.          0.         -1.16666667  0.        ]
 [ 0.          0.          1.         -0.66666667  0.        ]]


In [327]:
row_index = 1
Column_index = variable_counts -1
print("Results {")
for row in agmented_matrix :
        print(f"X{row_index} = X4*{-row[Column_index]}")
        row_index -=-1
print("X4 is FREE varable\n}")
print(f"Reduced Echlon Matrix:\n{agmented_matrix}")

Results {
X1 = X4*0.3333333333333333
X2 = X4*1.1666666666666665
X3 = X4*0.6666666666666666
X4 is FREE varable
}
Reduced Echlon Matrix:
[[ 1.          0.          0.         -0.33333333  0.        ]
 [ 0.          1.          0.         -1.16666667  0.        ]
 [ 0.          0.          1.         -0.66666667  0.        ]]


In [ ]:
success_count = 0
first_integer_resault = 1
key_number = 2
while True :
    for row in agmented_matrix :
        multiple = key_number*(-row[Column_index])
        res = multiple - int(multiple)
        if res == 0 or res > 0.8999999999999999:
            success_count -=-1
    if success_count == row_index:
        first_integer_resault = key_number
        break
    else : 
        success_count = 0
        key_number-=-1

first_integer_resault

In [326]:
row_index = 1
Column_index = variable_counts -1
print("Results {")
for row in agmented_matrix :
        print(f"X{row_index} = {int((-row[Column_index] * first_integer_resault).round())}")
        row_index -=-1
print(f"X4 = {first_integer_resault}"+"\n}")

Results {
X1 = 2
X2 = 7
X3 = 4
X4 = 6
}
