In [12]:
import matplotlib.pyplot as plt
import numpy as np

In [13]:
firstArray = np.arange(10,dtype=float)
secondArray = np.arange(10,20,dtype=float)
print(f"First Array:\n{firstArray}")
print(f"secondArray:\n{secondArray}")

First Array:
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
secondArray:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]


In [14]:
def toeplitz_maker(firstArray,secondArray):
    first_array_len = len(firstArray) -1 
    second_array_len = len(secondArray) -1 
    toeplitz_array = np.arange((first_array_len)*(second_array_len),dtype=float).reshape(first_array_len,second_array_len)
    print(f'toeplitz array shape: {toeplitz_array.shape}')
    second_index = second_array_len
    col_index = 0
    while col_index < second_array_len:
        dif_index = second_array_len -col_index 
        if(col_index!= 0):
            col_index_temp = col_index +1
            index = 0
            while col_index_temp >= 1 :
                toeplitz_array[index,col_index] = secondArray[col_index_temp]
                col_index_temp-=1
                index -=-1
                
            col_index_temp = 1
            
            for i in range(index,first_array_len+1):
                   toeplitz_array[i-1,col_index] = firstArray[col_index_temp] 
                   col_index_temp -=-1
        else:
            for i in range(1,first_array_len+1):
                 toeplitz_array[i-1,col_index] = firstArray[i]       
        col_index -=-1   
            
        
    return toeplitz_array 
    

In [15]:
toeplitz_array  = toeplitz_maker(firstArray,secondArray)
print(f"toeplitz array:\n{toeplitz_array }")

toeplitz array shape: (9, 9)
toeplitz array:
[[ 1. 12. 13. 14. 15. 16. 17. 18. 19.]
 [ 2.  1. 12. 13. 14. 15. 16. 17. 18.]
 [ 3.  2.  1. 12. 13. 14. 15. 16. 17.]
 [ 4.  3.  2.  1. 12. 13. 14. 15. 16.]
 [ 5.  4.  3.  2.  1. 12. 13. 14. 15.]
 [ 6.  5.  4.  3.  2.  1. 12. 13. 14.]
 [ 7.  6.  5.  4.  3.  2.  1. 12. 13.]
 [ 8.  7.  6.  5.  4.  3.  2.  1. 12.]
 [ 9.  8.  7.  6.  5.  4.  3.  2.  1.]]


In [16]:
np.linalg.det(toeplitz_array)

2974862719.999997

In [17]:
index = 0
for column_index in range(0,toeplitz_array.shape[0]):
    for row_index in range(index + 1,toeplitz_array.shape[1]):
        if toeplitz_array[row_index,column_index] != 0:
            toeplitz_array[row_index,:] -= toeplitz_array[index,:]*toeplitz_array[row_index,column_index]/toeplitz_array[index,column_index]
    
    index -=-1
    
print("Echlon Form of toeplitz", toeplitz_array)

determinan = 1
for last_index in range(0,toeplitz_array.shape[0]):
    determinan *= toeplitz_array[last_index,last_index]

print("Determinant:  ", determinan)

Echlon Form of toeplitz [[ 1.00000000e+00  1.20000000e+01  1.30000000e+01  1.40000000e+01
   1.50000000e+01  1.60000000e+01  1.70000000e+01  1.80000000e+01
   1.90000000e+01]
 [ 0.00000000e+00 -2.30000000e+01 -1.40000000e+01 -1.50000000e+01
  -1.60000000e+01 -1.70000000e+01 -1.80000000e+01 -1.90000000e+01
  -2.00000000e+01]
 [ 0.00000000e+00  0.00000000e+00 -1.73043478e+01 -7.82608696e+00
  -8.34782609e+00 -8.86956522e+00 -9.39130435e+00 -9.91304348e+00
  -1.04347826e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.54271357e+01
  -5.78894472e+00 -6.15075377e+00 -6.51256281e+00 -6.87437186e+00
  -7.23618090e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -1.45029316e+01 -4.78436482e+00 -5.06579805e+00 -5.34723127e+00
  -5.62866450e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00 -1.39586740e+01 -4.19153715e+00 -4.42440032e+00
  -4.65726350e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0